-- Seed some sample movies for Staff Picks
INSERT INTO movies (title, poster_url, rating, description, genres, runtime, year, cast_members, where_to_watch, staff_pick, featured)
VALUES
  (
    'Dune: Part Two',
    '/placeholder.svg?height=450&width=300',
    8.8,
    'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    ARRAY['Sci-Fi', 'Adventure', 'Drama'],
    166,
    2024,
    ARRAY['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
    '{"netflix": null, "prime": "https://amazon.com/dune2", "hbo": "https://max.com/dune2", "apple": "https://tv.apple.com/dune2", "hulu": null}',
    true,
    true
  ),
  (
    'Oppenheimer',
    '/placeholder.svg?height=450&width=300',
    8.9,
    'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    ARRAY['Drama', 'Biography', 'History'],
    180,
    2023,
    ARRAY['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    '{"netflix": null, "prime": "https://amazon.com/oppenheimer", "hbo": null, "apple": "https://tv.apple.com/oppenheimer", "hulu": null}',
    true,
    true
  ),
  (
    'Poor Things',
    '/placeholder.svg?height=450&width=300',
    8.3,
    'The incredible tale of Bella Baxter, a young woman brought back to life by an unorthodox scientist.',
    ARRAY['Comedy', 'Drama', 'Romance', 'Sci-Fi'],
    141,
    2023,
    ARRAY['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'],
    '{"netflix": null, "prime": null, "hbo": "https://max.com/poorthings", "apple": "https://tv.apple.com/poorthings", "hulu": "https://hulu.com/poorthings"}',
    true,
    false
  ),
  (
    'The Holdovers',
    '/placeholder.svg?height=450&width=300',
    7.9,
    'A curmudgeonly instructor at a New England prep school remains on campus during Christmas break to babysit students.',
    ARRAY['Comedy', 'Drama'],
    133,
    2023,
    ARRAY['Paul Giamatti', 'Da''Vine Joy Randolph', 'Dominic Sessa'],
    '{"netflix": null, "prime": "https://amazon.com/holdovers", "hbo": null, "apple": "https://tv.apple.com/holdovers", "hulu": null}',
    true,
    false
  ),
  (
    'Past Lives',
    '/placeholder.svg?height=450&width=300',
    8.1,
    'Two childhood friends are separated after one''s family emigrates from South Korea. Twenty years later, they are reunited for one week in New York.',
    ARRAY['Drama', 'Romance'],
    106,
    2023,
    ARRAY['Greta Lee', 'Teo Yoo', 'John Magaro'],
    '{"netflix": null, "prime": "https://amazon.com/pastlives", "hbo": null, "apple": "https://tv.apple.com/pastlives", "hulu": null}',
    true,
    false
  ),
  (
    'Interstellar',
    '/placeholder.svg?height=450&width=300',
    8.7,
    'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
    ARRAY['Sci-Fi', 'Adventure', 'Drama'],
    169,
    2014,
    ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    '{"netflix": null, "prime": "https://amazon.com/interstellar", "hbo": "https://max.com/interstellar", "apple": "https://tv.apple.com/interstellar", "hulu": null}',
    true,
    false
  ),
  (
    'Everything Everywhere All at Once',
    '/placeholder.svg?height=450&width=300',
    8.0,
    'A middle-aged Chinese immigrant is swept up into an insane adventure where she alone can save existence.',
    ARRAY['Action', 'Adventure', 'Comedy', 'Sci-Fi'],
    139,
    2022,
    ARRAY['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'Jamie Lee Curtis'],
    '{"netflix": "https://netflix.com/eeaao", "prime": "https://amazon.com/eeaao", "hbo": null, "apple": "https://tv.apple.com/eeaao", "hulu": null}',
    true,
    false
  ),
  (
    'The Batman',
    '/placeholder.svg?height=450&width=300',
    7.8,
    'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate.',
    ARRAY['Action', 'Crime', 'Drama'],
    176,
    2022,
    ARRAY['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Colin Farrell'],
    '{"netflix": null, "prime": null, "hbo": "https://max.com/thebatman", "apple": "https://tv.apple.com/thebatman", "hulu": null}',
    false,
    false
  ),
  (
    'Barbie',
    '/placeholder.svg?height=450&width=300',
    7.0,
    'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.',
    ARRAY['Comedy', 'Adventure', 'Fantasy'],
    114,
    2023,
    ARRAY['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
    '{"netflix": null, "prime": null, "hbo": "https://max.com/barbie", "apple": "https://tv.apple.com/barbie", "hulu": null}',
    false,
    false
  ),
  (
    'The Godfather',
    '/placeholder.svg?height=450&width=300',
    9.2,
    'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    ARRAY['Crime', 'Drama'],
    175,
    1972,
    ARRAY['Marlon Brando', 'Al Pacino', 'James Caan'],
    '{"netflix": null, "prime": "https://amazon.com/godfather", "hbo": "https://max.com/godfather", "apple": "https://tv.apple.com/godfather", "hulu": null}',
    true,
    false
  ),
  (
    'Amélie',
    '/placeholder.svg?height=450&width=300',
    8.3,
    'Amélie is an innocent and naive girl in Paris with her own sense of justice.',
    ARRAY['Comedy', 'Romance'],
    122,
    2001,
    ARRAY['Audrey Tautou', 'Mathieu Kassovitz'],
    '{"netflix": null, "prime": "https://amazon.com/amelie", "hbo": null, "apple": "https://tv.apple.com/amelie", "hulu": "https://hulu.com/amelie"}',
    true,
    false
  ),
  (
    'Spirited Away',
    '/placeholder.svg?height=450&width=300',
    8.6,
    'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    ARRAY['Animation', 'Adventure', 'Family', 'Fantasy'],
    125,
    2001,
    ARRAY['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'],
    '{"netflix": "https://netflix.com/spiritedaway", "prime": null, "hbo": "https://max.com/spiritedaway", "apple": "https://tv.apple.com/spiritedaway", "hulu": null}',
    true,
    false
  );
